#ifndef __RT_AI_PARTS_CLASSIFICATION_MODEL_H
#define __RT_AI_PARTS_CLASSIFICATION_MODEL_H

#include <parts_classification.h>
#include <parts_classification_data.h>

/* model info ... */

// model name
#define RT_AI_PARTS_CLASSIFICATION_MODEL_NAME			"parts_classification"
#define RT_AI_PARTS_CLASSIFICATION_WORK_BUFFER_BYTES		AI_PARTS_CLASSIFICATION_DATA_ACTIVATIONS_SIZE
#define RT_AI_PARTS_CLASSIFICATION_DATA_WEIGHTS_SIZE		AI_PARTS_CLASSIFICATION_DATA_WEIGHTS_SIZE

#define RT_AI_PARTS_CLASSIFICATION_BUFFER_ALIGNMENT		AI_PARTS_CLASSIFICATION_ACTIVATIONS_ALIGNMENT

#define RT_AI_PARTS_CLASSIFICATION_IN_NUM				AI_PARTS_CLASSIFICATION_IN_NUM
#define RT_AI_PARTS_CLASSIFICATION_IN_1_SIZE				AI_PARTS_CLASSIFICATION_IN_1_SIZE
#define RT_AI_PARTS_CLASSIFICATION_IN_1_SIZE_BYTES		AI_PARTS_CLASSIFICATION_IN_1_SIZE_BYTES
#define RT_AI_PARTS_CLASSIFICATION_IN_TOTAL_SIZE_BYTES	(AI_PARTS_CLASSIFICATION_IN_1_SIZE_BYTES)
#define RT_AI_PARTS_CLASSIFICATION_IN_SIZE_BYTES			{AI_PARTS_CLASSIFICATION_IN_1_SIZE_BYTES}


#define RT_AI_PARTS_CLASSIFICATION_OUT_NUM				AI_PARTS_CLASSIFICATION_OUT_NUM
#define RT_AI_PARTS_CLASSIFICATION_OUT_1_SIZE			AI_PARTS_CLASSIFICATION_OUT_1_SIZE
#define RT_AI_PARTS_CLASSIFICATION_OUT_1_SIZE_BYTES		AI_PARTS_CLASSIFICATION_OUT_1_SIZE_BYTES
#define RT_AI_PARTS_CLASSIFICATION_OUT_TOTAL_SIZE_BYTES	(AI_PARTS_CLASSIFICATION_OUT_1_SIZE_BYTES)
#define RT_AI_PARTS_CLASSIFICATION_OUT_SIZE_BYTES		{AI_PARTS_CLASSIFICATION_OUT_1_SIZE_BYTES}


#define RT_AI_PARTS_CLASSIFICATION_TOTAL_BUFFER_SIZE		(NULL)		//unused

#endif	//end
